version: '3'
services:
  gateway:
    image: "gsuveti/spring-zuul:latest"
    ports:
      - "8080:8080"
    environment:
      - GRAFANA_HOST=grafana
      - AUTHORIZATION_SERVER_HOST=authorization
      - SHOP_HOST=shop
      - BLOG_HOST=blog

  authorization:
    image: "gsuveti/spring-authorization:latest"
    ports:
      - "8081:8081"

  blog:
    image: "gsuveti/resource-blog:latest"
    ports:
      - "8083:8083"

  shop:
    image: "gsuveti/resource-shop:latest"
    ports:
      - "8084:8084"
