version: '3'
services:
  gateway:
    image: "gsuveti/spring-zuul:latest"
    ports:
      - "8080:8080"
    environment:
      - GRAFANA_HOST=grafana
      - AUTHORIZATION_SERVER_HOST=authorization
      - SHOP_HOST=shop
      - BLOG_HOST=blog

  authorization:
    image: "gsuveti/spring-authorization:latest"

  blog:
    image: "irianro/resource-blog:latest"
    ports:
      - "8083:8083"
    environment:
      - "ACTIVEMQ_URL=tcp://activemq:61616"
      - "ACTIVEMQ_USER=admin"
      - "ACTIVEMQ_PASSWORD=admin"

  shop:
    image: "gsuveti/resource-shop:latest"
    ports:
      - "8084:8084"

  activemq:
    image: "rmohr/activemq"
    ports:
      - "8161:8161"
      - "61616:61616"
